"""V8.5 recovery statuses. Fail closed. Not an execution kernel."""

from __future__ import annotations

from enum import Enum


MAX_RECOVERY_ATTEMPTS = 1


class RecoveryFailureClass(str, Enum):
    SUCCESS = "SUCCESS"
    TIMEOUT = "TIMEOUT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    NOT_VERIFIED = "NOT_VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    STEP_FAILED = "STEP_FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    ABORTED = "ABORTED"
    EMERGENCY_STOPPED = "EMERGENCY_STOPPED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    PLAN_HASH_MISMATCH = "PLAN_HASH_MISMATCH"
    INVALID_PLAN = "INVALID_PLAN"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    ACTION_UNAVAILABLE = "ACTION_UNAVAILABLE"
    SESSION_UNAVAILABLE = "SESSION_UNAVAILABLE"
    V8_DISABLED = "V8_DISABLED"
    UNKNOWN = "UNKNOWN"


class RecoveryStatus(str, Enum):
    SUCCESS = "SUCCESS"
    NO_RECOVERY = "NO_RECOVERY"
    PROPOSED = "PROPOSED"
    EXECUTED = "EXECUTED"
    TERMINAL = "TERMINAL"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    V8_DISABLED = "V8_DISABLED"
    INVALID_INPUT = "INVALID_INPUT"
    RECURSIVE_RECOVERY = "RECURSIVE_RECOVERY"
    ATTEMPT_LIMIT = "ATTEMPT_LIMIT"


class RecoveryAction(str, Enum):
    NONE = "NONE"
    RETRY_IDEMPOTENT_STEP = "RETRY_IDEMPOTENT_STEP"
    RETRY_VERIFICATION = "RETRY_VERIFICATION"
