"""V11.1 Execution Layer.

Executes plans generated by the V10 cognitive architecture using the V8 execution
system while maintaining the HARD $0 recurring-cost requirement and integrating
with existing V8 authorization, verification, and safety systems.
"""

from __future__ import annotations

import time
from typing import Optional

from core.v10.planning_integration import PlanningResult
from orchestration.executor import ExecutionIdentity, execute_plan, ExecutionResult
from orchestration.executor_errors import ExecutionStatus
from orchestration.goal.plan_types import GoalPlan


class ExecutionLayer:
    """V11.1 Execution Layer.
    
    Executes plans generated by V10.5 planning integration using the V8 executor.
    Maintains strict owner-scoped state and integrates with V8 authorization
    and safety systems.
    """

    def __init__(self):
        """Initialize the execution layer."""
        pass

    def execute_plan(
        self,
        planning_result: PlanningResult,
        owner_id: str,
        session_id: str = "",
        authorized_plan_hash: str = "",
        computer_session_id: str = ""
    ) -> ExecutionResult:
        """Execute a plan generated by V10.5 planning integration.
        
        Args:
            planning_result: The result from V10.5 planning integration
            owner_id: Owner ID for scoping and isolation
            session_id: Session ID for scoping
            authorized_plan_hash: Authorized plan hash for approved plans
            computer_session_id: Computer session ID if available
            
        Returns:
            ExecutionResult from executing the plan, or a PlanningResult
            wrapped in an ExecutionResult if planning did not succeed
        """
        start_time = time.time()
        
        # If planning was not required or not successful, return an execution result
        # that reflects this state without attempting execution
        if not planning_result.planning_required or not planning_result.planning_successful:
            return self._create_execution_result_from_planning_result(
                planning_result, start_time, ExecutionStatus.SUCCESS
            )
        
        # If we have a plan, execute it using the V8 executor
        if planning_result.plan is not None:
            return self._execute_v8_plan(
                planning_result.plan, owner_id, session_id, start_time,
                authorized_plan_hash=authorized_plan_hash,
                computer_session_id=computer_session_id
            )
        
        # If we somehow got here without a plan despite planning being successful,
        # return an error
        return self._create_error_execution_result(
            start_time, 
            ExecutionStatus.INVALID_PLAN,
            "Planning successful but no plan was generated"
        )

    def _execute_v8_plan(
        self,
        plan: GoalPlan,
        owner_id: str,
        session_id: str,
        start_time: float,
        authorized_plan_hash: str = "",
        computer_session_id: str = ""
    ) -> ExecutionResult:
        """Execute a plan using the V8 executor.
        
        Args:
            plan: The GoalPlan to execute
            owner_id: Owner ID for scoping
            session_id: Session ID for scoping
            start_time: Start time for timing calculations
            authorized_plan_hash: Authorized plan hash
            computer_session_id: Computer session ID
            
        Returns:
            ExecutionResult from the V8 executor
        """
        # Resolve computer session ID: parameter takes precedence, fallback to plan attribute
        comp_session = computer_session_id or getattr(plan, "computer_session_id", "") or ""
        
        # Create an execution identity for the V8 executor
        identity = ExecutionIdentity(
            owner_id=owner_id,
            session_id=session_id,
            computer_session_id=comp_session
        )
        
        # Execute the plan using the V8 executor
        # Propagate authorized_plan_hash so pre-approved plans can execute
        execution_result = execute_plan(
            plan=plan,
            identity=identity,
            authorized_plan_hash=authorized_plan_hash
        )
        
        return execution_result

    def _create_execution_result_from_planning_result(
        self,
        planning_result: PlanningResult,
        start_time: float,
        status: ExecutionStatus
    ) -> ExecutionResult:
        """Create an ExecutionResult from a PlanningResult when no execution occurs.
        
        Args:
            planning_result: The planning result to convert
            start_time: Start time for timing calculations
            status: The ExecutionStatus to set
            
        Returns:
            ExecutionResult representing the planning outcome
        """
        from orchestration.executor import _result
        
        # When no planning was required, verification is NOT_APPLICABLE for tools
        v_state = "NOT_APPLICABLE" if not planning_result.planning_required else ""
        
        return _result(
            plan=None,  # No plan was executed
            status=status,
            verification=v_state,
            start=int(start_time * 1000),
            end=int(time.time() * 1000)
        )

    def _create_error_execution_result(
        self,
        start_time: float,
        status: ExecutionStatus,
        error_message: str
    ) -> ExecutionResult:
        """Create an error ExecutionResult.
        
        Args:
            start_time: Start time for timing calculations
            status: The ExecutionStatus to set
            error_message: Error message to include
            
        Returns:
            ExecutionResult representing the error
        """
        from orchestration.executor import _result
        
        return _result(
            plan=None,
            status=status,
            start=int(start_time * 1000),
            end=int(time.time() * 1000),
            response_text=error_message
        )


# Global instance for convenience
execution_layer = ExecutionLayer()


def execute_plan_from_planning_result(
    planning_result: PlanningResult,
    owner_id: str,
    session_id: str = "",
    authorized_plan_hash: str = "",
    computer_session_id: str = ""
) -> ExecutionResult:
    """Convenience function for V11.1 execution layer.
    
    Args:
        planning_result: The result from V10.5 planning integration
        owner_id: Owner ID for scoping and isolation
        session_id: Session ID for scoping
        authorized_plan_hash: Authorized plan hash
        computer_session_id: Computer session ID
        
    Returns:
        ExecutionResult from executing the plan
    """
    return execution_layer.execute_plan(
        planning_result, owner_id, session_id,
        authorized_plan_hash=authorized_plan_hash,
        computer_session_id=computer_session_id
    )