"""V8.4 orchestrator statuses. Fail closed. Not a computer kernel."""

from __future__ import annotations

from enum import Enum


class ExecutionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    V8_DISABLED = "V8_DISABLED"
    PLAN_HASH_MISMATCH = "PLAN_HASH_MISMATCH"
    INVALID_PLAN = "INVALID_PLAN"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SESSION_UNAVAILABLE = "SESSION_UNAVAILABLE"
    IDENTITY_REQUIRED = "IDENTITY_REQUIRED"
    AUTHORIZATION_INVALID = "AUTHORIZATION_INVALID"
    AUTHORIZATION_EXPIRED = "AUTHORIZATION_EXPIRED"
    AUTHORIZATION_REVOKED = "AUTHORIZATION_REVOKED"
    AUTHORIZATION_CONSUMED = "AUTHORIZATION_CONSUMED"
    RISK_NOT_APPROVABLE = "RISK_NOT_APPROVABLE"
    PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
    COMPUTER_SESSION_REQUIRED = "COMPUTER_SESSION_REQUIRED"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    ACTION_UNAVAILABLE = "ACTION_UNAVAILABLE"
    EMERGENCY_STOPPED = "EMERGENCY_STOPPED"
    STEP_FAILED = "STEP_FAILED"
    NOT_VERIFIED = "NOT_VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    TIMEOUT = "TIMEOUT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    STALE_OBSERVATION_HASH = "STALE_OBSERVATION_HASH"
    ABORTED = "ABORTED"
    CANCELLED = "ABORTED"
