import re
import random
from typing import List, Dict, Any, Optional
from models.base_provider import BaseLLMProvider, LLMResponse

class FallbackProvider(BaseLLMProvider):
    """Zero-Config Local Autonomous Provider that routes intents to Tool Registry & Knowledge Base"""
    name = "fallback"

    def is_available(self) -> bool:
        return True  # Always available

    def generate(self,
                 prompt: str,
                 system_prompt: str = "",
                 tools: Optional[List[Dict[str, Any]]] = None,
                 temperature: float = 0.7) -> LLMResponse:
        p_lower = prompt.lower().strip()
        tool_calls = []

        # 1. App Launching Intent
        if any(p_lower.startswith(p) for p in ["open ", "launch ", "start "]):
            app_name = re.sub(r'^(open|launch|start)\s+(the\s+)?(app\s+|application\s+|program\s+)?', '', p_lower).strip()
            if app_name:
                tool_calls.append({
                    "id": "call_open_app",
                    "name": "computer_open_app",
                    "arguments": {"app_name": app_name}
                })
                return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 2. YouTube Music Intent
        if p_lower.startswith("play ") or p_lower in ["play music", "play songs", "play a song"]:
            query = re.sub(r'^(play|stream)\s+(song\s+|music\s+|video\s+)?', '', p_lower).strip()
            if not query or query in ["music", "song", "media", "songs", "something"]:
                query = "lofi hip hop beats to relax study to"
            tool_calls.append({
                "id": "call_stream_youtube",
                "name": "computer_stream_youtube",
                "arguments": {"query": query}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 3. Weather Intent
        if "weather" in p_lower:
            city = "current"
            if "in " in p_lower:
                try:
                    city = p_lower.split("in ")[-1].replace("today", "").replace("now", "").strip()
                except Exception:
                    pass
            tool_calls.append({
                "id": "call_weather",
                "name": "web_weather",
                "arguments": {"city": city}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 4. News Intent
        if "news" in p_lower:
            topic = "general"
            if "about " in p_lower:
                try:
                    topic = p_lower.split("about ")[-1].strip()
                except Exception:
                    pass
            tool_calls.append({
                "id": "call_news",
                "name": "web_news",
                "arguments": {"topic": topic}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 5. Stock Price Intent
        if "stock" in p_lower or "share price" in p_lower:
            symbol = re.sub(r'^(what is the|check|get|what\'s the)?\s*(stock price of|stock price|stock|share price of|share price)\s+', '', p_lower).strip()
            if symbol:
                tool_calls.append({
                    "id": "call_stock",
                    "name": "web_stock_price",
                    "arguments": {"symbol": symbol}
                })
                return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 6. Coding Intent
        if any(w in p_lower for w in ["write code", "write a code", "write python", "generate code", "create script", "python code"]):
            # Generate appropriate python code
            if "snake" in p_lower:
                code = "# Snake Game generated by DOOM V2\nimport turtle, time, random\nprint('Snake game initialized!')\n"
                fname = "snake_game.py"
            elif "prime" in p_lower:
                code = "# Prime Numbers\ndef primes(n):\n    return [x for x in range(2, n) if all(x % d != 0 for d in range(2, int(x**0.5) + 1))]\nprint('First primes up to 50:', primes(50))\n"
                fname = "prime_calculator.py"
            else:
                code = f"# Script Generated for Sujal\nimport datetime\nprint('DOOM Task Executed successfully at', datetime.datetime.now())\n"
                fname = "doom_generated_task.py"
            
            tool_calls.append({
                "id": "call_write_script",
                "name": "coding_write_script",
                "arguments": {"file_name": fname, "code": code}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 7. System Diagnostics & Screenshot
        if "screenshot" in p_lower or "capture screen" in p_lower:
            tool_calls.append({
                "id": "call_screenshot",
                "name": "system_take_screenshot",
                "arguments": {}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        if any(k in p_lower for k in ["system status", "system info", "cpu", "ram", "memory usage"]):
            tool_calls.append({
                "id": "call_system_status",
                "name": "system_get_status",
                "arguments": {}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        if any(k in p_lower for k in ["lock pc", "lock computer", "lock screen"]):
            tool_calls.append({
                "id": "call_lock_pc",
                "name": "system_lock_pc",
                "arguments": {}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 8. Vision & Gesture Detection
        if any(k in p_lower for k in ["gesture", "detect hand", "read hand"]):
            tool_calls.append({
                "id": "call_gesture",
                "name": "vision_scan_gesture",
                "arguments": {"duration_seconds": 5}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 9. Database & Telemetry Query Intent
        if any(k in p_lower for k in ["database status", "db status", "check database", "check db", "postgres status"]):
            tool_calls.append({
                "id": "call_db_status",
                "name": "database_status",
                "arguments": {}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        if any(k in p_lower for k in ["database telemetry", "db telemetry", "telemetry history", "hardware logs"]):
            tool_calls.append({
                "id": "call_db_telemetry",
                "name": "database_get_telemetry",
                "arguments": {"limit": 5}
            })
            return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/rule_engine")

        # 10. Boss Identity & Persona
        if any(w in p_lower for w in ["who am i", "what is my name", "do you know me"]):
            return LLMResponse(
                text="You are Sujal, my creator, boss, and lead engineer. I am at your command, sir.",
                tool_calls=[],
                model_name="fallback/persona"
            )

        if any(w in p_lower for w in ["who are you", "what is your name", "who made you", "who created you"]):
            return LLMResponse(
                text="I am DOOM V2, your high-tech Personal AI Operating System, engineered by Sujal to operate your workstation and automate all workflows. We are DOOM.",
                tool_calls=[],
                model_name="fallback/persona"
            )

        # 10. General Web Search Fallback
        tool_calls.append({
            "id": "call_web_search",
            "name": "web_search",
            "arguments": {"query": prompt}
        })
        return LLMResponse(text="", tool_calls=tool_calls, model_name="fallback/web_search")
